---
# handlers file for ansible-role-git-lfs

# This action is required on RedHat 6 system
- name: RedHat | yum makecache
  ansible.builtin.command: yum -q makecache -y --disablerepo='*' --enablerepo='github_git-lfs'
